-- Insertar debilidades
INSERT INTO monstruo_debilidades (monstruo_id, debilidades) VALUES
    (1, 'LUZ_SOLAR'), (1, 'AGUA_BENDITA'),
    (2, 'AJO'), (2, 'LUZ_SOLAR'),
    (3, 'DISPARO_CABEZA'), (3, 'FUEGO'),
    (4, 'FUEGO'), (4, 'AGUA_BENDITA'),
    (5, 'PLATA'), (5, 'LUZ_SOLAR'),
    (6, 'PLATA'), (6, 'FUEGO'),
    (7, 'RITUALES_SAGRADOS'), (7, 'RUIDOS_FUERTES'),
    (8, 'FUEGO_SAGRADO'), (8, 'AMULETOS_PROTECTORES'),
    (9, 'SAL_SAGRADA'), (9, 'FUEGO_SAGRADO'),
    (10, 'PLATA'), (10, 'RITUALES_SAGRADOS'),
    (11, 'LUZ_SAGRADA'), (11, 'FUEGO'),
    (12, 'AGUA_BENDITA'), (12, 'FUEGO'),
    (13, 'FUEGO'), (13, 'AGUA_BENDITA'),
    (14, 'FUEGO_SAGRADO'), (14, 'PLATA'),
    (15, 'LUZ_SAGRADA'), (15, 'FUEGO_SAGRADO'),
    (16, 'AGUA_BENDITA'), (16, 'SAL_SAGRADA'),
    (17, 'FUEGO'), (17, 'RAYOS'),
    (18, 'LUZ_SOLAR'), (18, 'FUEGO'),
    (19, 'FUEGO_SAGRADO'), (19, 'AGUA_BENDITA'),
    (20, 'FUEGO'), (20, 'SAL_SAGRADA'),
    (21, 'LUZ_SAGRADA'), (21, 'PLATA'),
    (22, 'LUZ_SOLAR'), (22, 'AMULETOS_PROTECTORES'),
    (23, 'FUEGO'), (23, 'LUZ_SOLAR'),
    (24, 'AGUA_BENDITA'), (24, 'SIMBOLOS_SAGRADOS'),
    (25, 'RUIDOS_FUERTES'), (25, 'LUZ_SOLAR'),
    (26, 'HIERRO_FRIO'), (26, 'FUEGO_SAGRADO');
