-- Insertar habilidades especiales
INSERT INTO monstruo_habilidades_especiales (monstruo_id, habilidades_especiales) VALUES
    (1, 'Control de mentes'),
    (1, 'Manipulación emocional'),
    (2, 'Control de sueños'),
    (2, 'Alteración de la percepción'),
    (3, 'Creación de zombis'),
    (3, 'Inmunidad a la muerte'),
    (4, 'Llamar a la horda'),
    (4, 'Aumento de fuerza'),
    (5, 'Regeneración'),
    (5, 'Fuerza sobrehumana'),
    (6, 'Camuflaje'),
    (6, 'Agilidad extrema'),
    (7, 'Controlar sombra'),
    (7, 'Oscuridad palpable'),
    (8, 'Llamar a los muertos'),
    (8, 'Comunicación con espíritus'),
    (9, 'Control de mentes'),
    (9, 'Manipulación de recuerdos'),
    (10, 'Llamar a criaturas'),
    (10, 'Telepatía'),
    (11, 'Ocultar aura de muerte'),
    (11, 'Inmunidad al temor'),
    (12, 'Engaño mental'),
    (12, 'Creación de ilusiones'),
    (13, 'Invocar fantasmas'),
    (13, 'Robo de almas'),
    (14, 'Predicción del futuro'),
    (14, 'Manipulación del tiempo'),
    (15, 'Influencia mental'),
    (15, 'Persuasión sobrenatural'),
    (16, 'Incendio infernal'),
    (16, 'Control de llamas'),
    (17, 'Emociones intensas'),
    (17, 'Manipulación de emociones'),
    (18, 'Invisibilidad'),
    (18, 'Desvanecimiento'),
    (19, 'Extracción de huesos'),
    (19, 'Reanimación'),
    (20, 'Invocar soldados esqueléticos'),
    (20, 'Control de los muertos'),
    (21, 'Engaño visual'),
    (21, 'Ilusiones ópticas'),
    (22, 'Fuga rápida'),
    (22, 'Desaparición instantánea'),
    (23, 'Camuflaje'),
    (23, 'Sigilo absoluto'),
    (24, 'Control del clima'),
    (24, 'Manipulación atmosférica'),
    (25, 'Apariciones'),
    (25, 'Viaje entre dimensiones'),
    (26, 'Creación de ilusiones'),
    (26, 'Desplazamiento ilusorio');

